api_platform:
    title: Pokemon API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        json: ['application/json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_items_per_page: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
