version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  database:
    image: postgres
    restart: always
    environment:
     - POSTGRES_DB=app
     - POSTGRES_PASSWORD=!ChangeMe!
     - POSTGRES_USER=app
    ports:
     - "5432:5432"
