App\Entity\Reward:
  attributes:
    name:
      groups: ['reward:write']
    condition:
      groups: ['reward:write']
    url:
      groups: ['reward:write']

App\Entity\Game:
  attributes:
    id:
      groups: [ 'game:read' ]
    name:
      groups: ['game:create', 'game:write', 'game:read']
    description:
      groups: ['game:create', 'game:write', 'game:read']
    questions:
      groups: ['game:create']

App\Entity\Question:
  attributes:
    id:
      groups: [ 'question:read' ]
    label:
      groups: ['game:create', 'question:write', 'question:read']
    media:
      groups: ['game:create', 'question:write', 'question:read']
    createdAt:
      groups: ['question:read']
    updatedAt:
      groups: ['question:read']

App\Entity\Choice:
  attributes:
    id:
      groups: [ 'question:read' ]
    label:
      groups: ['game:create', 'question:write', 'question:read']
    isCorrect:
      groups: ['game:create', 'question:write', 'question:read']

App\Entity\User:
  attributes:
    id:
      groups: [ 'user:read' ]
    email:
      groups: ['user:read']
    roles:
      groups: ['user:read']
    createdAt:
      groups: ['user:read']
    experience:
      groups: ['user:read']