App\Entity\Reward:
  attributes:
    name:
      groups: ['reward:write']
    unlockPoints:
      groups: ['reward:write']
    url:
      groups: ['reward:write']

App\Entity\Game:
  attributes:
    id:
      groups: [ 'game:read' ]
    name:
      groups: ['game:create', 'game:write', 'game:read']
    description:
      groups: ['game:create', 'game:write', 'game:read']

App\Entity\User:
  attributes:
    id:
      groups: [ 'user:read' ]
    email:
      groups: ['user:read']
    roles:
      groups: ['user:read']
    createdAt:
      groups: ['user:read']
    experience:
      groups: ['user:read']