controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_doc:
    path: /
    controller: api_platform.swagger_ui.action

auth:
    path: /auth
    methods: ['POST']