resources:
  App\Entity\User:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
    normalizationContext:
      groups: [ 'user:read' ]

  App\Entity\UserProfile:
    - operations:
        ApiPlatform\Metadata\Get:
          output: false
          read: false
          controller: ApiPlatform\Action\NotFoundAction
          openapi: false
    - uriTemplate: /users/{id}/profile
      uriVariables:
        id:
          fromClass: App\Entity\User
          fromProperty: profile
      operations:
        ApiPlatform\Metadata\Get: ~
        ApiPlatform\Metadata\Patch: ~

  App\Entity\GameSession:
    uriTemplate: /users/{id}/sessions
    uriVariables:
      id:
        fromClass: App\Entity\User
        fromProperty: sessions
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~

  App\Entity\Level:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

  App\Entity\Game:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

  App\Entity\Reward:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post:
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
    denormalizationContext:
      groups: [ 'reward:write' ]

  App\Entity\Avatar:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

  App\Entity\UserReward:
    - uriTemplate: /users/{id}/rewards
      uriVariables:
        id:
          fromClass: App\Entity\User
          fromProperty: userRewards
      operations:
        ApiPlatform\Metadata\GetCollection: ~
        ApiPlatform\Metadata\Post: ~
    - uriTemplate: /users/{id}/rewards/{rewardId}
      uriVariables:
        id:
          fromClass: App\Entity\User
          fromProperty: userRewards
        rewardId:
          fromClass: App\Entity\UserReward
      operations:
        ApiPlatform\Metadata\Delete: ~

  App\Entity\UserAvatar:
    - uriTemplate: /users/{id}/avatars
      uriVariables:
        id:
          fromClass: App\Entity\User
          fromProperty: userAvatars
      operations:
        ApiPlatform\Metadata\GetCollection: ~
        ApiPlatform\Metadata\Post: ~
    - uriTemplate: /users/{id}/avatars/{rewardId}
      uriVariables:
        id:
          fromClass: App\Entity\User
          fromProperty: userAvatars
        rewardId:
          fromClass: App\Entity\UserAvatar
      operations:
        ApiPlatform\Metadata\Delete: ~