resources:
  App\Entity\User:
    - operations:
        ApiPlatform\Metadata\GetCollection: ~
        ApiPlatform\Metadata\Post: ~
        ApiPlatform\Metadata\Get: ~
        ApiPlatform\Metadata\Put: ~
        ApiPlatform\Metadata\Patch: ~
        ApiPlatform\Metadata\Delete: ~

  App\Entity\Level:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Put: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~

  App\Entity\Game:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Put: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
    normalizationContext:
      groups: [ 'game:read' ]
    denormalizationContext:
      groups: [ 'game:write' ]

  App\Entity\Reward:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post:
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Put: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~
    denormalizationContext:
      groups: [ 'reward:write' ]

  App\Entity\Avatar:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Post: ~
      ApiPlatform\Metadata\Get: ~
      ApiPlatform\Metadata\Put: ~
      ApiPlatform\Metadata\Patch: ~
      ApiPlatform\Metadata\Delete: ~